"""
analyze.py — POST /analyze endpoint.
Merges URL features, network signals, and permission signals into one
XGBoost prediction with SHAP explanation.
"""

import logging
from datetime import datetime, timezone
from typing import Annotated
from urllib.parse import urlparse

import tldextract
from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field, HttpUrl, StringConstraints
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.database import get_db
from backend.feature_extractor.url_features import extract_url_features
from backend.models.scan import Scan
from backend.rate_limit import limiter
from backend.services.heuristics_engine import evaluate
from backend.services.virustotal_client import get_domain_info
from ml.shap_analysis import ModelUnavailableError, explain_prediction

logger = logging.getLogger(__name__)

router = APIRouter()


# ── Request / Response schemas ────────────────────────────────────────────────

# Caps below are all generous relative to any real page (chrome.storage.local's own signal
# collectors cap far lower than this in practice) — they exist only to bound worst-case JSONB
# storage and downstream processing (e.g. url_features.py's brand-impersonation check, which does
# an edit-distance comparison per hostname token) for a caller that isn't the extension at all,
# since nothing about this endpoint requires the request to have actually come from it.
_MAX_STR_LIST_ITEMS = 100
_ShortStr = Annotated[str, StringConstraints(max_length=256)]


class NetworkSignals(BaseModel):
    tracker_count: int = Field(default=0, ge=0, le=10_000)
    has_mixed_content: bool = False
    redirect_chain_length: int = Field(default=0, ge=0, le=1_000)
    third_party_domains: list[_ShortStr] = Field(
        default_factory=list, max_length=_MAX_STR_LIST_ITEMS
    )


class PermissionSignals(BaseModel):
    permissions_requested: list[_ShortStr] = Field(
        default_factory=list, max_length=_MAX_STR_LIST_ITEMS
    )
    rule_flags: list[_ShortStr] = Field(default_factory=list, max_length=_MAX_STR_LIST_ITEMS)


class ScamContentSignals(BaseModel):
    scam_keyword_hits: int = Field(default=0, ge=0, le=10_000)
    matched_phrases: list[_ShortStr] = Field(
        default_factory=list, max_length=_MAX_STR_LIST_ITEMS
    )
    sensitive_field_count: int = Field(default=0, ge=0, le=1_000)
    sensitive_field_categories: list[_ShortStr] = Field(
        default_factory=list, max_length=_MAX_STR_LIST_ITEMS
    )


class AnalyzeRequest(BaseModel):
    url: HttpUrl = Field(..., max_length=2048)
    network_signals: NetworkSignals | None = None
    permission_signals: PermissionSignals | None = None
    scam_content_signals: ScamContentSignals | None = None
    # Per-browser-install id generated by the extension (chrome.storage.local), used to scope
    # /history and /stats to the browser that produced each scan. Not an authenticated identity.
    client_id: str | None = Field(default=None, max_length=64)


class ShapReason(BaseModel):
    feature: str
    value: float | int | bool | str | None
    shap_impact: float
    human_readable: str


class AnalyzeResponse(BaseModel):
    scan_id: str
    verdict: str           # "phishing" | "suspicious" | "legitimate"
    risk_score: float      # Raw probability, 0.0 – 1.0
    risk_pct: int           # round(risk_score * 100) — how phishing-like the page is (ADR-015)
    confidence_pct: int    # round(max(p, 1-p) * 100) — how decisive the model is (ADR-015)
    top_reasons: list[ShapReason]
    flagged_rules: list[str]


# Reduce a URL to its registrable domain (e.g. "sub.example.co.uk" -> "example.co.uk").
def _extract_domain(url: str) -> str:
    parsed = urlparse(url)
    # Falls back to "", never to the raw url string: url is validated by Pydantic's HttpUrl before
    # this runs, so parsed.hostname should never actually be empty, but if it somehow were, this
    # value is interpolated unescaped into an outbound request URL in virustotal_client.py — an
    # empty string is handled safely there (get_domain_info returns the -1 defaults immediately),
    # whereas the raw url could carry a path/query/fragment straight into that request.
    hostname = parsed.hostname or ""
    extracted = tldextract.extract(hostname)
    if extracted.domain and extracted.suffix:
        return f"{extracted.domain}.{extracted.suffix}"
    return hostname


# Fuse URL, network, permission, page-content, and VirusTotal signals into one verdict, and persist
# it. VT is fetched synchronously — it now genuinely participates in the fused score (see
# risk_fusion.py's asymmetric vt_malicious_votes weight: a VT hit raises the score, but a clean or
# unavailable VT result contributes nothing, since blocklist-derived data has zero recall on URLs
# no one has reported yet — the same failure mode as the B1 blocklist baseline). That means every
# scan waits on VT's own latency (bounded by virustotal_client.py's timeout) and free-tier rate
# limit (4/min) — a deliberate trade-off requested explicitly, not an oversight: VT can only ever
# push a verdict toward "worse," so its absence from a fast path is not equivalent to it running
# after the fact.
@router.post("/analyze", response_model=AnalyzeResponse)
@limiter.limit("10/minute")
async def analyze_url(
    request: Request, body: AnalyzeRequest, db: AsyncSession = Depends(get_db)
):
    # slowapi's decorator requires a starlette Request parameter literally named `request` to key
    # the rate limit off the caller's address — the request body (previously named `request`) is
    # `body` here instead; nothing below reads the raw Request object directly.
    url = str(body.url)
    network_signals = (
        body.network_signals.model_dump() if body.network_signals else None
    )
    permission_signals = (
        body.permission_signals.model_dump() if body.permission_signals else None
    )
    scam_content_signals = (
        body.scam_content_signals.model_dump() if body.scam_content_signals else None
    )

    domain = _extract_domain(url)
    vt_data = await get_domain_info(domain)

    rule_flags, heuristic_features = evaluate(
        network_signals,
        permission_signals,
        scam_content_signals,
    )

    url_features = extract_url_features(url, vt_data=vt_data)
    feature_vector = {**url_features, **heuristic_features}

    try:
        analysis = explain_prediction(feature_vector)
    except ModelUnavailableError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    # Re-analyzing a URL already scanned by this browser updates that row instead of accumulating
    # a new one — one row per (client_id, url), always current. Only attempted with a real
    # client_id: without one there's no safe way to tell "the same browser's earlier scan" apart
    # from unrelated anonymous traffic, so that case always inserts fresh (existing behaviour).
    scan = None
    if body.client_id:
        scan = await db.scalar(
            select(Scan).where(Scan.client_id == body.client_id, Scan.url == url)
        )

    now = datetime.now(timezone.utc)
    if scan is not None:
        scan.verdict = analysis["label"]
        scan.risk_score = analysis["score"]
        scan.risk_pct = analysis["risk_pct"]
        scan.confidence_pct = analysis["confidence_pct"]
        scan.url_features = url_features
        scan.network_signals = network_signals
        scan.permission_signals = permission_signals
        scan.scam_content_signals = scam_content_signals
        scan.shap_values = analysis["top_reasons"]
        scan.flagged_rules = rule_flags
        scan.last_scanned_at = now
    else:
        scan = Scan(
            url=url,
            client_id=body.client_id,
            verdict=analysis["label"],
            risk_score=analysis["score"],
            risk_pct=analysis["risk_pct"],
            confidence_pct=analysis["confidence_pct"],
            url_features=url_features,
            network_signals=network_signals,
            permission_signals=permission_signals,
            scam_content_signals=scam_content_signals,
            shap_values=analysis["top_reasons"],
            flagged_rules=rule_flags,
            last_scanned_at=now,
        )
        db.add(scan)

    await db.commit()
    await db.refresh(scan)

    return AnalyzeResponse(
        scan_id=str(scan.id),
        verdict=scan.verdict,
        risk_score=scan.risk_score,
        risk_pct=scan.risk_pct,
        confidence_pct=scan.confidence_pct,
        top_reasons=scan.shap_values or [],
        flagged_rules=scan.flagged_rules or [],
    )
