"""create_scans_table

Revision ID: ab476f0dcf44
Revises: 
Create Date: 2026-08-08 17:13:34.374830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab476f0dcf44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence_pct', sa.Integer(), nullable=False),
    sa.Column('url_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('network_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permission_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flagged_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_url'), 'scans', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_url'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
