"""
scan.py — SQLAlchemy ORM model for scan records.
One row per (client_id, url) pair, kept up to date rather than accumulated: re-analyzing a URL
already scanned by the same browser updates that row in place instead of inserting a new one.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Float, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from backend.database import Base


class Scan(Base):
    """Stores one phishing analysis result per URL visit."""

    __tablename__ = "scans"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    # Per-browser-install identifier generated by the extension (chrome.storage.local), not a
    # real user account. Scopes /history and /stats so one browser never sees another's scans.
    client_id: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    url: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    verdict: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # "phishing" | "suspicious" | "legitimate"
    risk_score: Mapped[float] = mapped_column(Float, nullable=False)
    # ADR-015: risk_pct = round(risk_score * 100); confidence_pct = round(max(p, 1-p) * 100) — a
    # separate, always-decisive quantity, not derivable from risk_pct by UI-side arithmetic.
    risk_pct: Mapped[int] = mapped_column(Integer, nullable=False)
    confidence_pct: Mapped[int] = mapped_column(Integer, nullable=False)

    # Raw feature dictionaries stored as JSONB
    url_features: Mapped[dict] = mapped_column(JSONB, nullable=True)
    network_signals: Mapped[dict] = mapped_column(JSONB, nullable=True)
    permission_signals: Mapped[dict] = mapped_column(JSONB, nullable=True)
    scam_content_signals: Mapped[dict] = mapped_column(JSONB, nullable=True)

    # SHAP output — list of {feature, value, shap_impact, human_readable}
    shap_values: Mapped[list] = mapped_column(JSONB, nullable=True)

    # Rule-based flags from heuristics engine
    flagged_rules: Mapped[list] = mapped_column(JSONB, nullable=True)

    # True creation time — never updated after the row's first insert, unlike everything above it.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    # When this URL was last analyzed for this client — set to created_at on insert, then bumped on
    # every re-scan. /history sorts by this, not created_at, so a re-checked URL surfaces as recent.
    last_scanned_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # Serialize to a plain dict for API responses. client_id is deliberately excluded — it's an
    # internal scoping value, and including it in a public response let a leaked scan_id (e.g. a
    # shared "look at this phishing site" dashboard link) pivot into full-history disclosure via
    # /history, since nothing else about client_id is a secret once it's read off a response body.
    def to_dict(self) -> dict:
        return {
            "scan_id": str(self.id),
            "url": self.url,
            "verdict": self.verdict,
            "risk_score": self.risk_score,
            "risk_pct": self.risk_pct,
            "confidence_pct": self.confidence_pct,
            "url_features": self.url_features,
            "network_signals": self.network_signals,
            "permission_signals": self.permission_signals,
            "scam_content_signals": self.scam_content_signals,
            "shap_values": self.shap_values,
            "flagged_rules": self.flagged_rules,
            "created_at": self.created_at.isoformat(),
            "last_scanned_at": self.last_scanned_at.isoformat(),
        }
